package com.example.springdatajpa.model;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@MappedSuperclass
public class BaseEntity {
    //Big serial data type will be generated by @sequence
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "student_sequence")
    @SequenceGenerator(name = "student_sequence", sequenceName = "student_sequence", allocationSize = 1)
    @Column(name = "id",
            nullable = false,
     updatable = false)
    private Long id;
}
